max_p: 5
max_q: 5
max_P: 1
max_Q: 1
m: 24
training_data_ratio: 0.8
traffic_data_root_dir: "../output/metr-imc-interpolated"

output_root_dir: "./output"
traffic_training_data_path: "../output/metr-imc-small/interpolated/time_mean_avg/metr-imc-01-absolute-simple/metr-imc.h5"
traffic_test_data_path: "../output/metr-imc-small/metr-imc-test.h5"

info:
  outlier_cleaning:
    - RemovingWeirdZeroOutlierProcessor
    - SimpleAbsoluteOutlierProcessor
  interpolation:
    - TimeMeanInterpolationProcessor