# Dataset
dataset: "metr-la"
n_his: 12           # Number of historical observations
n_pred: 3
time_intvl: 5

# Model
Kt: 3
stblock_num: 2
act_func: "glu"
Ks: 3
graph_conv_type: "cheb_graph_conv"
gso_type: "sym_norm_lap"
enable_bias: true
droprate: 0.5

# Training
seed: 42
lr: 0.001
weight_decay_rate: 0.001
batch_size: 32
epochs: 1000
patience: 10

# Optimizer
optimizer: "lion"
step_size: 10
gamma: 0.95

# Hardware
device: mps
